### ISSUE TITLE
Bug on Altay

### ISSUE THREAD

**Issue by SuperAdam47** [CzechPMDevs/MultiWorld#21]
- Issue Description:
![image](https://user-images.githubusercontent.com/16169771/42938366-b88d52ba-8b5a-11e8-8bc3-55a4bbdc14f6.png)

- Version: 1.5

- Server Version: 1.7

- Crashdump, backtrace or other files:

**Comment by XuPaperCup** [comment]
Me too:
![image](https://user-images.githubusercontent.com/32026718/42982765-6e0da33c-8c15-11e8-85aa-88ef62c2a226.png)

This error is cause by a ender generator.It is because pocketmine didn't have ender before,but now it have so you can see the error massage : Alias "ender" already assigned,which mean ender already have
and the plugin use ender generator.It is the same bug in #18 but it was about nether.So to fix this,I recommend to delete ender generator,I will create a pull requests later.

**Comment by GamakCZ** [comment]
Use PocketMine to fix this "issue"

**Comment by SuperAdam47** [comment]
📦
