### ISSUE TITLE
Killing the cpu and memory on the server

### ISSUE THREAD

**Issue by liveguysytcoder** [CzechPMDevs/MultiWorld#293]
**Describe the bug**
It's just can't run able to run the server on 2.05GB ram using during the player join the server the cpu get 185% uses I don't know why but i finally go the answer because when I remove multiworld it work fine! 
Normal so only the problem is Multiworld so pls fix it!

**Comment by liveguysytcoder** [comment]
The only problem the multiworld plugin is using high cpu and memory on the server to load chunks and worlds!

**Comment by VixikHD** [comment]
High CPU usage is caused by generator. You are probably generating a world with Custom world generator. Either use less expensive generator shipped with PocketMine ("normal_old", "nether_old", "flat") or limit chunk generation with some border plugin. However, the after those chunks are generated your CPU usage should get at its normal level.

2GB rams are enough, also, you can attach more CPUs for the generator in order to make the generation faster.

**Comment by liveguysytcoder** [comment]
I am using flat than also why it's just?

**Comment by VixikHD** [comment]
Flat should not cause problems. Can we move this chat on to [discord server](https://discord.gg/YdRVQSwcfH
), please?
