### ISSUE TITLE
Add per-world inventories

### ISSUE THREAD

**Issue by Bruth78** [CzechPMDevs/MultiWorld#49]
Could you add the option of per world inventories?
And maybe the option to block commands?
Great Plugin btw

**Comment by GamakCZ** [comment]
Good idea, although suitable. There is small problem. PMMP has too outdated api for world management. Normall vanilla levels has worlds made so every level has own nether and end. But pmmp has just several worlds. The problem is because player must have same items in every dimension in one world... I can made plugin for that if you want.

**Comment by diamondkorben** [comment]
Make that plugin
